# main text of home
name: Yang Liu
bio: Welcome to my personal website! I am a linguist and a language instructor. I received my PhD in Linguistics from Stony Brook University. My research areas are phonology, Chinese linguistics, phonetics, first/second language acquisition, syntax-prosody interface and computational linguistics. 

# twitter summary info
#description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: true
picture: assets/images/1.jpg

# If you want to include your resume, set to true
# and specify source (external or local).

#resume: true

url: https://yliucloud.github.io
your url: http://yliucloud.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus: false
#  shortname: mydisqus # enter this from your disqus account
#  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: twitter
#google: https://www.google.com/
# instagram: myinstagram
# pinterest: mypinterest
#linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: yliucloud
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: yang.liu.11[_at_]stonybrook.edu

authors:
    johndoe:
        name: John Doe
        bio: A Man who travels the world eating noodles
        external-image: false
        picture: assets/images/profile.jpg
        twitter: johndoe
    jamesfoster:
        name: James Foster
        bio: A Man who develops software with coffee
        external-image: false
        picture: assets/images/james.jpg
        twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
#projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# show next & prev links in blog post?
blog-nav-links: false

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
